base:
  tie_apiurl: "https://foo.bar/api/"
  tie_apikey: "12345683127481209123789"
  misp_apiurl: "https://misp.foo.bar"
  misp_apikey: "asd22asdt9898asdfj120asd9213jas"
  misp_verifycert: "False"
  base_severity: 3
  base_confidence: 60

organisation:
  name: "ACME"
  uuid: "5804adw2-12fe-1234-34av-07lk82aw012a"

events:
  base_threat_level: "3"
  published: "False"
  info_c2server: "TIE Daily C2Server"
  info_malware: "TIE Daily Malware"
  base_confidence: "80"
  base_severity: "2"

attributes:
  to_ids: "False"
  tagging: "False"

